tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "act"
brew "fzy"
brew "openssl@1.1"
brew "krb5"
brew "libpq"
brew "node-build"
brew "nodenv"
brew "pgcli"
brew "postgresql@14", restart_service: true
brew "python@3.10"
brew "rbenv"
brew "redis", restart_service: true
brew "skaffold"
brew "tree"
brew "zola"
brew "heroku/brew/heroku"
cask "google-cloud-sdk"
cask "react-native-debugger"
